theme: jekyll-theme-minima
title: ADA Template Website
description: A template website for ADA
markdown: kramdown
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
